"""Curated career-site configurations for target companies."""

from config import USER_PROFILE

# ats: greenhouse | lever | ashby | smartrecruiters | workday
# slug: board identifier. Workday uses '{host}/{site}'.
KNOWN_ATS = {
    "Adobe": {"ats": "workday", "slug": "adobe.wd5.myworkdayjobs.com/external_experienced"},
    "Airbnb": {"ats": "greenhouse", "slug": "airbnb"},
    "Broadcom": {"ats": "workday", "slug": "broadcom.wd1.myworkdayjobs.com/External_Career"},
    "BrowserStack": {"ats": "workday", "slug": "browserstack.wd3.myworkdayjobs.com/External"},
    "Canonical": {"ats": "greenhouse", "slug": "canonical"},
    "Capital One": {"ats": "workday", "slug": "capitalone.wd12.myworkdayjobs.com/Capital_One"},
    "Cisco": {"ats": "workday", "slug": "cisco.wd5.myworkdayjobs.com/Cisco_Careers"},
    "Cloudflare": {"ats": "greenhouse", "slug": "cloudflare"},
    "Cockroach Labs": {"ats": "greenhouse", "slug": "cockroachlabs"},
    "Confluent": {"ats": "ashby", "slug": "confluent"},
    "CRED": {"ats": "lever", "slug": "cred"},
    "CrowdStrike": {"ats": "workday", "slug": "crowdstrike.wd5.myworkdayjobs.com/crowdstrikecareers"},
    "Databricks": {"ats": "greenhouse", "slug": "databricks"},
    "Datadog": {"ats": "greenhouse", "slug": "datadog"},
    "Druva": {"ats": "greenhouse", "slug": "druva"},
    "eBay": {"ats": "workday", "slug": "ebay.wd5.myworkdayjobs.com/apply"},
    "Elastic": {"ats": "greenhouse", "slug": "elastic"},
    "Fastly": {"ats": "greenhouse", "slug": "fastly"},
    "Fi": {"ats": "lever", "slug": "epifi"},
    "Freshworks": {"ats": "smartrecruiters", "slug": "Freshworks"},
    "GitLab": {"ats": "greenhouse", "slug": "gitlab"},
    "Glance": {"ats": "greenhouse", "slug": "glance"},
    "Grafana Labs": {"ats": "greenhouse", "slug": "grafanalabs"},
    "Groww": {"ats": "greenhouse", "slug": "groww"},
    "HackerRank": {"ats": "greenhouse", "slug": "hackerrank"},
    "HighRadius": {"ats": "greenhouse", "slug": "highradius"},
    "InMobi": {"ats": "greenhouse", "slug": "inmobi"},
    "LinkedIn": {"ats": "greenhouse", "slug": "linkedin"},
    "Mastercard": {"ats": "workday", "slug": "mastercard.wd1.myworkdayjobs.com/CorporateCareers"},
    "Meesho": {"ats": "lever", "slug": "meesho"},
    "Mindtickle": {"ats": "lever", "slug": "mindtickle"},
    "MongoDB": {"ats": "greenhouse", "slug": "mongodb"},
    "Navi": {"ats": "ashby", "slug": "navi"},
    "Netomi": {"ats": "lever", "slug": "netomi"},
    "New Relic": {"ats": "greenhouse", "slug": "newrelic"},
    "NVIDIA": {"ats": "workday", "slug": "nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite"},
    "Observe.AI": {"ats": "greenhouse", "slug": "observeai"},
    "Okta": {"ats": "greenhouse", "slug": "okta"},
    "Paytm": {"ats": "lever", "slug": "paytm"},
    "PhonePe": {"ats": "greenhouse", "slug": "phonepe"},
    "Porter": {"ats": "lever", "slug": "porter"},
    "Postman": {"ats": "greenhouse", "slug": "postman"},
    "Razorpay": {"ats": "greenhouse", "slug": "razorpaysoftwareprivatelimited"},
    "Red Hat": {"ats": "workday", "slug": "redhat.wd5.myworkdayjobs.com/jobs"},
    "Redis": {"ats": "ashby", "slug": "redis"},
    "Rubrik": {"ats": "greenhouse", "slug": "rubrik"},
    "Salesforce": {"ats": "workday", "slug": "salesforce.wd12.myworkdayjobs.com/External_Career_Site"},
    "ServiceNow": {"ats": "smartrecruiters", "slug": "ServiceNow"},
    "Slice": {"ats": "greenhouse", "slug": "slice"},
    "Snowflake": {"ats": "ashby", "slug": "snowflake"},
    "Sprinklr": {"ats": "workday", "slug": "sprinklr.wd1.myworkdayjobs.com/careers"},
    "Sumo Logic": {"ats": "greenhouse", "slug": "sumologic"},
    "Swiggy": {"ats": "smartrecruiters", "slug": "swiggy"},
    "Synechron": {"ats": "workday", "slug": "synechron.wd1.myworkdayjobs.com/SynechronCareers"},
    "Target": {"ats": "workday", "slug": "target.wd5.myworkdayjobs.com/targetcareers"},
    "Thoughtworks": {"ats": "greenhouse", "slug": "thoughtworks"},
    "Triomics": {"ats": "ashby", "slug": "triomics"},
    "Twilio": {"ats": "greenhouse", "slug": "twilio"},
    "Uber": {"ats": "smartrecruiters", "slug": "Uber"},
    "Unacademy": {"ats": "smartrecruiters", "slug": "Unacademy"},
    "Uniphore": {"ats": "workday", "slug": "uniphore.wd503.myworkdayjobs.com/Uniphore"},
    "Visa": {"ats": "workday", "slug": "visa.wd5.myworkdayjobs.com/Visa"},
    "Zeta": {"ats": "lever", "slug": "zeta"},
    "Zscaler": {"ats": "greenhouse", "slug": "zscaler"},
}

# Career page URLs used to auto-discover ATS slugs when not in KNOWN_ATS
CAREER_URLS = {
    "Google": "https://careers.google.com/jobs/results/",
    "Meta": "https://www.metacareers.com/jobs",
    "Microsoft": "https://careers.microsoft.com/us/en/search-results",
    "Amazon": "https://www.amazon.jobs/en/search",
    "Apple": "https://jobs.apple.com/en-us/search",
    "Netflix": "https://jobs.netflix.com/search",
    "Uber": "https://www.uber.com/us/en/careers/list/",
    "Airbnb": "https://careers.airbnb.com/",
    "LinkedIn": "https://careers.linkedin.com/",
    "Salesforce": "https://salesforce.wd12.myworkdayjobs.com/External_Career_Site",
    "Databricks": "https://www.databricks.com/company/careers/open-positions",
    "Snowflake": "https://careers.snowflake.com/us/en/search-results",
    "Atlassian": "https://www.atlassian.com/company/careers/all-jobs",
    "Adobe": "https://adobe.wd5.myworkdayjobs.com/external_experienced",
    "NVIDIA": "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
    "SAP": "https://jobs.sap.com/",
    "SAP Labs": "https://jobs.sap.com/go/India/8807201/",
    "VMware": "https://careers.vmware.com/main/jobs",
    "Cisco": "https://cisco.wd5.myworkdayjobs.com/Cisco_Careers",
    "ServiceNow": "https://careers.servicenow.com/",
    "Intuit": "https://jobs.intuit.com/search-jobs",
    "PayPal": "https://paypal.eightfold.ai/careers",
    "Oracle": "https://careers.oracle.com/en/sites/jobsearch/jobs",
    "Oracle (OCI)": "https://www.oracle.com/careers/opportunities/oracle-cloud-infrastructure/",
    "Expedia Group": "https://careers.expediagroup.com/jobs/",
    "MakeMyTrip": "https://careers.makemytrip.com/",
    "Electronic Arts": "https://ea.gr8people.com/jobs",
    "Qualcomm": "https://careers.qualcomm.com/careers",
    "Walmart Global Tech": "https://tech.walmart.com/content/technology-us/en/tools/careers.html",
    "JPMorgan Chase": "https://careers.jpmorgan.com/us/en/students/programs/software-engineer-fulltime",
    "Morgan Stanley": "https://morganstanley.eightfold.ai/careers",
    "Goldman Sachs": "https://higher.gs.com/results",
    "Cohesity": "https://careers.cohesity.com/",
    "Rubrik": "https://www.rubrik.com/company/careers",
    "Zoho": "https://www.zoho.com/careers/job-openings.html",
    "Freshworks": "https://careers.freshworks.com/",
    "Chargebee": "https://www.chargebee.com/careers/",
    "Twilio": "https://www.twilio.com/en-us/careers",
    "Kissflow": "https://kissflow.com/careers/",
    "Postman": "https://www.postman.com/company/careers/",
    "BrowserStack": "https://browserstack.wd3.myworkdayjobs.com/External",
    "Razorpay": "https://razorpay.com/jobs/",
    "CRED": "https://careers.cred.club/",
    "Meesho": "https://careers.meesho.com/",
    "Swiggy": "https://careers.swiggy.com/",
    "Myntra": "https://careers.myntra.com/",
    "PhonePe": "https://www.phonepe.com/careers/",
    "ClearTax": "https://cleartax.in/s/careers",
    "Unacademy": "https://unacademy.com/careers",
    "ShareChat": "https://sharechat.com/careers",
    "Flipkart": "https://www.flipkartcareers.com/",
    "Zomato": "https://www.zomato.com/careers",
    "Groww": "https://groww.in/careers",
    "Visa": "https://visa.wd5.myworkdayjobs.com/Visa",
    "Mastercard": "https://mastercard.wd1.myworkdayjobs.com/CorporateCareers",
    "American Express": "https://aexp.eightfold.ai/careers",
    "Bloomberg": "https://www.bloomberg.com/company/careers/apply/",
    "Broadcom": "https://broadcom.wd1.myworkdayjobs.com/External_Career",
    "Booking.com": "https://jobs.booking.com/",
    "Walmart": "https://careers.walmart.com/",
    "Target": "https://target.wd5.myworkdayjobs.com/targetcareers",
    "eBay": "https://ebay.wd5.myworkdayjobs.com/apply",
    "Capital One": "https://capitalone.wd12.myworkdayjobs.com/Capital_One",
    "Barclays": "https://joinus.barclays/",
    "Deutsche Bank": "https://careers.db.com/",
    "UBS": "https://www.ubs.com/global/en/careers.html",
    "Cashfree": "https://www.cashfree.com/careers",
    "Juspay": "https://juspay.io/careers",
    "Pine Labs": "https://www.pinelabs.com/careers",
    "BharatPe": "https://bharatpe.com/careers",
    "Paytm": "https://jobs.lever.co/paytm",
    "Navi": "https://jobs.ashbyhq.com/navi",
    "Jupiter": "https://jupiter.money/careers",
    "Fi": "https://jobs.lever.co/epifi",
    "Zeta": "https://jobs.lever.co/zeta",
    "MobiKwik": "https://www.mobikwik.com/careers",
    "Slice": "https://job-boards.greenhouse.io/slice",
    "Open": "https://open.money/careers",
    "Zerodha": "https://careers.zerodha.com/",
    "Upstox": "https://upstox.com/careers/",
    "Angel One": "https://www.angelone.in/careers",
    "CoinDCX": "https://coindcx.com/careers",
    "CoinSwitch": "https://coinswitch.co/careers",
    "Smallcase": "https://www.smallcase.com/careers",
    "Zepto": "https://www.zeptonow.com/careers",
    "Blinkit": "https://blinkit.com/careers",
    "BigBasket": "https://careers.bigbasket.com/",
    "AJIO": "https://www.ajio.com/ajiocareers",
    "Nykaa": "https://www.nykaa.com/careers",
    "Lenskart": "https://careers.lenskart.com/",
    "FirstCry": "https://www.firstcry.com/careers",
    "Urban Company": "https://www.urbancompany.com/careers",
    "Udaan": "https://udaan.com/careers",
    "Delhivery": "https://www.delhivery.com/careers",
    "Shadowfax": "https://www.shadowfax.in/careers",
    "Porter": "https://jobs.lever.co/porter",
    "Rapido": "https://rapido.bike/careers",
    "Ola": "https://www.olacabs.com/careers",
    "BlackBuck": "https://www.blackbuck.com/careers",
    "Dream11": "https://www.dream11.com/careers",
    "Dream Sports": "https://www.dreamsports.tech/careers",
    "Moj": "https://mojapp.in/careers",
    "Glance": "https://job-boards.greenhouse.io/glance",
    "Druva": "https://www.druva.com/careers",
    "Whatfix": "https://whatfix.com/careers/",
    "MoEngage": "https://www.moengage.com/careers/",
    "CleverTap": "https://clevertap.com/careers/",
    "Hasura": "https://hasura.io/careers",
    "Gupshup": "https://www.gupshup.io/careers",
    "Uniphore": "https://uniphore.wd503.myworkdayjobs.com/Uniphore",
    "Darwinbox": "https://darwinbox.com/careers",
    "LeadSquared": "https://www.leadsquared.com/careers",
    "HighRadius": "https://www.highradius.com/careers",
    "InMobi": "https://www.inmobi.com/company/careers",
    "Media.net": "https://careers.media.net/",
    "Amagi": "https://www.amagi.com/careers",
    "ThoughtSpot": "https://www.thoughtspot.com/careers",
    "Sprinklr": "https://sprinklr.wd1.myworkdayjobs.com/careers",
    "HackerRank": "https://www.hackerrank.com/careers",
    "HackerEarth": "https://www.hackerearth.com/careers",
    "Wingify": "https://wingify.com/careers",
    "Observe.AI": "https://www.observe.ai/careers",
    "Simplilearn": "https://www.simplilearn.com/careers",
    "Scaler": "https://www.scaler.com/careers",
    "UpGrad": "https://upgrad.darwinbox.in/ms/candidate/careers",
    "Eruditus": "https://careers.emeritus.org/",
    "Datadog": "https://careers.datadoghq.com/",
    "Cloudflare": "https://www.cloudflare.com/careers/jobs/",
    "Grafana Labs": "https://grafana.com/about/careers/open-positions/",
    "Elastic": "https://jobs.elastic.co/",
    "Confluent": "https://www.confluent.io/careers/",
    "MongoDB": "https://www.mongodb.com/careers",
    "Redis": "https://redis.io/careers/",
    "Cockroach Labs": "https://www.cockroachlabs.com/careers/",
    "GitHub": "https://www.github.careers/careers-home",
    "GitLab": "https://about.gitlab.com/jobs/",
    "HashiCorp": "https://www.hashicorp.com/careers",
    "DigitalOcean": "https://www.digitalocean.com/careers",
    "Akamai": "https://akamaijobs.wd5.myworkdayjobs.com/External_Career",
    "Fastly": "https://www.fastly.com/about/careers",
    "New Relic": "https://newrelic.com/about/careers",
    "Splunk": "https://www.splunk.com/en_us/careers.html",
    "Sumo Logic": "https://www.sumologic.com/company/careers",
    "Dynatrace": "https://careers.dynatrace.com/",
    "Zscaler": "https://www.zscaler.com/careers",
    "Palo Alto Networks": "https://jobs.paloaltonetworks.com/",
    "CrowdStrike": "https://crowdstrike.wd5.myworkdayjobs.com/crowdstrikecareers",
    "Okta": "https://www.okta.com/company/careers/",
    "Auth0": "https://auth0.com/careers",
    "Wiz": "https://www.wiz.io/careers",
    "SentinelOne": "https://www.sentinelone.com/careers/",
    "Nutanix": "https://www.nutanix.com/company/careers",
    "Red Hat": "https://redhat.wd5.myworkdayjobs.com/jobs",
    "Canonical": "https://canonical.com/careers",
    "Hiver": "https://hiverhq.com/careers",
    "ShopDeck": "https://www.shopdeck.com/careers",
    "Attentive.ai": "https://www.attentive.ai/careers",
    "Netomi": "https://www.netomi.com/careers",
    "Snapmint": "https://www.snapmint.com/careers",
    "Triomics": "https://www.triomics.com/careers",
    "WeWork": "https://www.wework.com/careers",
    "Apna": "https://apna.co/careers",
    "Ather": "https://www.atherenergy.com/careers",
    "Simpl": "https://www.simpl.com/careers",
    "Unstop": "https://unstop.com/careers",
    "Moglix": "https://www.moglix.com/careers",
    "OfBusiness": "https://www.ofbusiness.com/careers",
    "Infra.Market": "https://infra.market/careers",
    "Cars24": "https://www.cars24.com/careers",
    "Spinny": "https://www.spinny.com/careers/",
    "CarDekho": "https://careers.cardekho.com/",
    "NoBroker": "https://www.nobroker.in/careers",
    "Housing.com": "https://housing.com/careers",
    "Policybazaar": "https://www.policybazaar.com/careers",
    "Acko": "https://www.acko.com/careers",
    "Digit": "https://www.godigit.com/careers",
    "Turtlemint": "https://www.turtlemint.com/careers",
    "Livspace": "https://www.livspace.com/in/careers",
    "Rupeek": "https://rupeek.com/careers",
    "Licious": "https://www.licious.in/careers",
    "Meatigo": "https://www.meatigo.com/careers",
    "PharmEasy": "https://pharmeasy.in/careers",
    "Tata 1mg": "https://www.1mg.com/careers",
    "Practo": "https://www.practo.com/company/careers",
    "HealthifyMe": "https://www.healthifyme.com/careers",
    "Cult.fit": "https://www.cult.fit/careers",
    "Mindtickle": "https://www.mindtickle.com/careers",
    "Innovaccer": "https://innovaccer.com/careers",
    "Nagarro": "https://www.nagarro.com/en/careers",
    "Thoughtworks": "https://www.thoughtworks.com/en-in/careers",
    "Publicis Sapient": "https://careers.publicissapient.com/",
    "EPAM": "https://www.epam.com/careers",
    "Globant": "https://www.globant.com/careers",
    "Synechron": "https://www.synechron.com/careers",
    "Persistent Systems": "https://www.persistent.com/careers/",
}

ALL_COMPANIES = USER_PROFILE.get("target_companies", [])


def get_career_config(company: str) -> dict:
    config = {"company": company, "career_url": CAREER_URLS.get(company, "")}

    if company in KNOWN_ATS:
        config.update(KNOWN_ATS[company])
    else:
        config["ats"] = None
        config["slug"] = None

    return config
